- name: Include distribution specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yaml'
        - '{{ ansible_os_family | lower }}.yaml'
        - default.yaml
      paths:
        - 'vars'
  tags: always

- name: Define repository
  import_tasks: repo.yaml
  tags: repository

- name: Install certbot
  import_tasks: certbot.yaml
  tags: certbot

- name: Install and configure nginx
  import_tasks: nginx.yaml
  tags: nginx
