---
- name: Include distribution specific vars
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yaml'
        - '{{ ansible_os_family | lower }}.yaml'
        - default.yaml
      paths:
        - 'vars'
  tags: always

- name: Define repository
  import_tasks: repo.yaml
  tags: repository

# name: Install dependencies
# import_tasks: deps.yaml

- name: Install and configure Loki
  import_tasks: loki.yaml
  tags: loki

- name: Install and configure Promtail
  import_tasks: promtail.yaml
  tags: promtail

- name: Install and configure Grafana
  import_tasks: grafana.yaml
  tags: grafana
