---
- name: ZZGrafana setup playbook
  hosts: localhost
  become: true
  vars:
    dedicated_lvs: true
    project_domain: zelenyzlon.in
    system_domain: monitoring.stefany.eu
    upgrade_rpms: false

    prometheus_web_external_url: https://monitoring.stefany.eu/prometheus
    prometheus_targets:
      node:
      - targets:
        - 192.168.2.1:9100
        labels:
          env: production
  vars_files:
    - grafana.yaml
    - modbus.yaml
    - users.yaml
  roles:
    - influxdata
#   - cloudalchemy.prometheus
#   - grafana
#   - nginx
