---
- name: Install role RPM dependencies
  dnf:
   name: ['python3-requests', 'python3-pip', 'ansible-collection-community-general']
   state: latest

- name: Install role pip dependencies
  pip:
    name: influxdb
